spring:
  redis:
    host: localhost
    port: 6379

resilience4j:
  ratelimiter:
    instances:
      apiServiceLimiter:
        limitForPeriod: 5          # 5 requests
        limitRefreshPeriod: 10s    # per 10 seconds
        timeoutDuration: 0         # no waiting
