spring:
  data:
    redis:
      host: localhost
      port: 6379

ratelimit:
  api:
    limit: 5          # API-level requests allowed per minute
    duration: 10      # in seconds
  user:
    limit: 3          # User-level requests allowed per minute
    duration: 60      # in seconds
